#HTKTOOLS_DIR="/cygdrive/f/rsync/RESEARCHS/small_vocabulary_/vs2008/htk/bin.win32/"
#HTKTOOLS_DIR="../../../small_vocabulary_/cygwin32/htk/HTKTools"
HTKTOOLS_DIR="../../../small_vocabulary_/HTK-3.4.1_pure/htk/HTKTools"
#datadir="../../../small_vocabulary_/datas/digit_rec_x240_v8"  #in unix used by 
#datadir="../../../small_vocabulary_/datas/digit_rec_x240_mc_array_level_50_boost_0db"
datadir="../../../small_vocabulary_/datas/x240_array_0_3_scaler_fan"
datadir="../../../small_vocabulary_/datas/v83_0comma3_scaler_fans"
datadir="../../../small_vocabulary_/datas/v8_4475_doublefans"
labdir=$datadir
wlabdir="../wavs/wlab"
trilab="../wavs/trilab"
outdir="../wavs/results"
