HTKTOOLS_DIR="/cygdrive/f/rsync/RESEARCHS/small_vocabulary_/vs2008/htk/bin.win32/"
HTKTOOLS_DIR="../../../small_vocabulary_/cygwin32/htk/HTKTools"
datadir="../../../small_vocabulary_/datas/digit_rec_x240_v8"  #in unix used by 
datadir="../../../small_vocabulary_/datas/digit_rec_x240_mc_array_level_50_boost_0db"
datadir="../../../small_vocabulary_/datas/digit_rec_x240_v8_n01_level0"
labdir=$datadir
wlabdir="../wavs/wlab"
trilab="../wavs/trilab"
outdir="../wavs/results"
